[workspace]
members = [
  "raycasting-2D",
  "prime-polars",
  "prime-spiral",
  "pathfinding",
  "penguin-spiral",
]

resolver = "2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
